global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    environment: 'dev'
    service: 'yfinance-service'

rule_files:
  - './alert.rules.yml'

scrape_configs:
  - job_name: 'yfinance-service'
    metrics_path: /metrics
    scrape_timeout: 5s
    static_configs:
      - targets: 
          - yfinance-service:8000
        labels:
          instance: 'main'

  - job_name: 'prometheus'
    static_configs:
      - targets: 
          - localhost:9090