name: Docker Build

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build Docker image
              run: docker build -t yfinance-service .