name: Docker Build

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Cache Docker layers
              uses: actions/cache@v4
              with:
                path: .cache/buildx
                key: buildx-${{ runner.os }}-${{ hashFiles('**/Dockerfile', '**/poetry.lock', '**/pyproject.toml') }}
                restore-keys: |
                  buildx-${{ runner.os }}-
            
            - name: Build image (no push)
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: yfinance-service:${{ github.sha }}
                cache-from: type=local,src=.cache/buildx
                cache-to: type=local,dest=.cache/buildx-new,mode=max
            - name: Move new cache
              if: always()
              run: |
                rm -rf .cache/buildx
                mv .cache/buildx-new .cache/buildx