name: CI Pipeline

on: 
    push:
        branches: [main]
    pull_request:

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        with:
            python-version: '3.13'

    test:
        uses: ./.github/workflows/test.yml
        with:
            python-version: '3.13'

    build:
        uses: ./.github/workflows/build.yml
        with:
            python-version: '3.13'
        needs: [lint, test]