name: CI Pipeline

on: 
    push:
        branches: [main]
    pull_request:

jobs:
    lint:
        name: Lint Code
        uses: ./.github/workflows/lint.yml
        with:
            python-version: '3.13'

    test:
        name: Run Tests
        uses: ./.github/workflows/test.yml
        with:
            python-version: '3.13'

    build:
        name: Build Docker Image
        uses: ./.github/workflows/build.yml
        with:
            python-version: '3.13'
        needs: [lint, test]