name: CI Pipeline

permissions:
  contents: read

defaults:
    run:
        shell: bash
env:
    CI: true

on: 
    push:
        branches: [main]
    pull_request:

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint Code
        uses: ./.github/workflows/lint.yml
        strategy:
          matrix:
            python-version: ['3.13']
          fail-fast: false
        with:
            python-version: ${{ matrix.python-version }}

    test:
        name: Run Tests
        uses: ./.github/workflows/test.yml
        strategy:
          matrix:
            python-version: ['3.13']
          fail-fast: false
        with:
            python-version: ${{ matrix.python-version }}

    build:
        name: Build Docker Image
        uses: ./.github/workflows/build.yml
        with:
            python-version: '3.13'
        needs: [lint, test]