name: CI Pipeline

permissions:
  contents: read

on: 
    push:
        branches: [main]
    pull_request:

jobs:
    lint:
        name: Lint Code
        uses: ./.github/workflows/lint.yml
        strategy:
          matrix:
            python-version: ['3.13']
        with:
            python-version: ${{ matrix.python-version }}

    test:
        name: Run Tests
        uses: ./.github/workflows/test.yml
        strategy:
          matrix:
            python-version: ['3.13']
        with:
            python-version: ${{ matrix.python-version }}

    build:
        name: Build Docker Image
        uses: ./.github/workflows/build.yml
        with:
            python-version: '3.13'
        needs: [lint, test]