name: Deploy on Release

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    if: ${{ github.event.release.target_commitish == 'main' }}
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo and tag
        id: set-vars
        run: |
          echo "repo=$(echo \"${GITHUB_REPOSITORY}\" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "tag=$(echo \"${RELEASE_TAG}\" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .  
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.set-vars.outputs.repo }}:${{ steps.set-vars.outputs.tag }}
            ghcr.io/${{ steps.set-vars.outputs.repo }}:latest
            ghcr.io/${{ steps.set-vars.outputs.repo }}:${{ github.sha }}
          cache-from: type=local,src=.cache/buildx
          cache-to: type=local,dest=.cache/buildx-new,mode=max


      - name: Scan image with Trivy (vuln check)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ steps.set-vars.outputs.repo }}:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"

      - name: Move new cache
        if: always()
        run: |
          rm -rf ./.cache/buildx
          mv ./.cache/buildx-new ./.cache/buildx

      - name: Deployment (placeholder)
        run: | 
          echo "Image pushed: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}"
          echo "Add your deploy step here (e.g. kubectl apply / helm upgrade / ssh deploy)"