name: Lint

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs: 
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # Set up Python environment
            - name: Setup & Install
              uses: ./.github/actions/setup-python-deps
              with:
                  python_version: ${{ inputs.python-version }}
                  development: true

            # Run Ruff (lint)
            - name: Lint with Ruff
              continue-on-error: true
              run: |
                poetry run ruff check app tests --output-format=github > ruff-report.txt
            - name: Upload Ruff report
              uses: actions/upload-artifact@v4
              with:
                name: ruff-report
                path: ruff-report.txt
            - name: Show Ruff report
              if: always()
              run: cat ruff-report.txt || echo "No Ruff report found"

            # Run Ruff (format)
            - name: Check formatting with Ruff
              continue-on-error: true
              run: |
                poetry run ruff format --check app tests
