name: Lint

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs: 
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                ref: ${{ github.event.pull_request.base.ref }}

            - name: Setup & Install
              uses: ./.github/actions/setup-python-deps
              with:
                  python_version: ${{ inputs.python-version }}
                  development: true

            - name: Lint with Ruff (annotations)
              continue-on-error: true
              run: |
                poetry run ruff check app tests --output-format=github | tee ruff-report.txt

            - name: Upload Ruff report
              uses: actions/upload-artifact@v5
              with:
                name: ruff-report-${{ inputs.python-version }}
                path: ruff-report.txt

            - name: Check formatting with Ruff
              continue-on-error: true
              run: poetry run ruff format --check app tests
