name: Create GitHub Release

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    tag-and-release:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/')
        steps:
            - uses: actions/checkout@v5

            - name: Extract version from branch
              id: extract
              run: |
                BRANCH="${GITHUB_REF##*/}"
                VERSION="${BRANCH#release/}"
                VERSION="${BRANCH#hotfix/}"
                echo "version=v$VERSION" >> "$GITHUB_OUTPUT"

            - name: Create Git tag
              uses: actions/github-script@v7
              with: 
                script: |
                    const tag = '${{ steps.extract.outputs.version }}';
                    const { repo, owner } = context.repo;
                    await github.rest.git.createRef({
                        owner,
                        repo,
                        ref: `refs/tags/${tag}`,
                        sha: context.sha
                    });
                    console.log(`✅ Created tag ${tag}`);

            - name: Create GitHub Release
              uses: actions/action-gh-release@v2
              with:
                tag_name: ${{ steps.extract.outputs.version }}
                name: "Release ${{ steps.extract.outputs.version }}"
                generate_release_notes: true