name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        description: 'Python version to use for testing'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup & Install
        uses: ./.github/actions/setup-python-deps
        with:
          python_version: ${{ inputs.python-version }}
      - name: Run tests
        run: poetry run pytest --maxfail=1 --disable-warnings --tb=short
      - name: Upload Pytest report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest-report.xml